# This is a basic workflow to help you get started with Actions

name: TfApply

# Controls when the workflow will run
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: 'actions/checkout@v4'

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"

      - uses: 'google-github-actions/auth@v2'
        with:
          service_account: 'github-actions@github-exploration-442503.iam.gserviceaccount.com'
          workload_identity_provider: 'projects/641246862184/locations/global/workloadIdentityPools/github/providers/nmcguirt-github'
      
      - name: Terraform fmt
        id: fmt
        run: |
          terraform fmt -check \
          -backend-config="bucket=${{vars.STATE_BUCKET}}" \
          -backend-config="prefix=terraform/${{env.GCP_PROJECT}}/state"
        continue-on-error: true
      
      - name: Terraform Init
        id: init
        run: |
          terraform init \
          -backend-config="bucket=${{vars.STATE_BUCKET}}" \
          -backend-config="prefix=terraform/${{env.GCP_PROJECT}}/state"
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      
      - name: Terraform Apply
        id: apply
        run: |
          terraform apply -auto-approve -compact-warnings -no-color \
          -backend-config="bucket=${{vars.STATE_BUCKET}}" \
          -backend-config="prefix=terraform/${{env.GCP_PROJECT}}/state"
        continue-on-error: true
        